File "generic_attr_constraint.php", line 8, characters 15-17:
Invalid xhp value for attribute :foo in my-xhp (Typing[4323])
File "generic_attr_constraint.php", line 3, characters 23-25:
Some type constraint(s) are violated here
File "generic_attr_constraint.php", line 3, characters 18-18:
T is a constrained type parameter
File "generic_attr_constraint.php", line 3, characters 23-25:
Expected num
File "generic_attr_constraint.php", line 8, characters 15-17:
But got string
